# Auto-generated by pipeline/adaptive_extractor.py — do not edit manually.
# New extractors are appended here after each successful adaptive run.
# Format: each extractor function is named _ext_NNN and registered in CUSTOM_EXTRACTORS.
from __future__ import annotations

from typing import Optional  # noqa: F401 (used by generated functions)

import re  # noqa: F401 (used by generated functions)
from bs4 import BeautifulSoup  # noqa: F401 (used by generated functions)

# List of (name: str, fn: callable) tuples tried in order by scraping_worker Tier 2c.
CUSTOM_EXTRACTORS: list = []
